config/routes.rb
Meifang::Application.routes.draw do
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/map', to: 'static_pages#map', via: 'get'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :categories
  mount Ckeditor::Engine => '/ckeditor'

  resources :information
  resources :new_homes
  resources :group_buyings
  resources :intention_to_registers
  resources :information_sharings
  resources :characters
  resources :about

  match '/intention_to_registers_new_homes', to: 'static_pages#get_new_homes', via: 'get'

end

app/models/information.rb
class Information < ActiveRecord::Base
  belongs_to :category
  belongs_to :new_home
  belongs_to :information_type

  validates :category, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :keywords, length: { maximum: 100 }
  validates :description, length: { maximum: 200 }

  mount_uploader :information_thumb, InformationThumbUploader

  searchable do
    integer :information_type_id
    integer :category_id
    text :title, :boost => 5
    text :description
    text :content
    time :created_at
  end
end

app/models/information_type.rb
class InformationType < ActiveRecord::Base
  has_many :information
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  add_breadcrumb "馨窝网首页", :root_path
  add_breadcrumb "资讯列表", :information_index_path

  def index

    @hot = Information.order('updated_at DESC').limit(8)
    @list = Information.order('hit DESC').limit(8)
    @information = Information.order('created_at DESC')
                              .paginate(page: params[:page])
                              .per_page(10)
    @information.total_entries = 1000 if(@information.total_entries > 1000)


    case params[:search_type]
      when "news"
        redirect_to URI.escape("http://#{params[:station]}.xinwowang.com/information?keyword=#{params[:keyword]}")
      when "new_homes"
        redirect_to URI.escape("http://#{params[:station]}.xinwowang.com/new_homes?keyword=#{params[:keyword]}")
      else
        @keyword = Sunspot.search(Information) do
          per_page = params[:per_page]
          if per_page.blank?
            per_page = 10
          else
            per_page = params[:per_page]
          end
          keywords params[:keyword]
          with(:information_type_id).equal_to(params[:information_type_id]) if params[:information_type_id].present?
          with(:category_id).equal_to(params[:category_id]) if params[:category_id].present?
          order_by :created_at, :desc
          paginate :page => params[:page], :per_page => per_page
        end

        @information = @keyword.results

        respond_to do |format|
          format.html
          format.json { render json: @information }
          format.js
        end

      end

  end

  def show
    

    @hot = Information.order('updated_at DESC').limit(8)
    @list = Information.order('hit DESC ').limit(8)
    @information = Information.find(params[:id])
    @new_home = NewHome.find_by_id(@information.new_home_id)
    if @information.hit.blank?
      @hit =rand(9)+1
    else
      @hit = @information.hit+rand(49)+1
    end
    @information.update_attribute(:hit, "#{@hit}" )

    add_breadcrumb "正文", information_path
  end
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_information.html.haml
%div{ style: "border-bottom:1px solid #CCC; margin-bottom:20px;" }
  %p.f16.cl
    = link_to information.title, information, :class => "f16 cl", target: "_blank"
  %p.f12.ch 标签：#{information.keywords}
  %p.f14
    = information.description
  %p.f12.ch
    #{information.created_at.strftime("%Y-%m-%d")} - 来源：#{information.source} -
    = link_to "预览", information

app/views/information/_right.html.haml
.pull-left.ml20
  %div{ style: "width:240px;" }
    %div.well{ style: "padding: 8px 0" }
      %ul.nav.nav-list
        %li.nav_header.f16
          &gt;
          %strong &nbsp;&nbsp;网站导航
        %li.f14.mt10
          = link_to " 楼盘速递", information_index_path(:category_id => 12)
          = link_to " 楼盘优惠", information_index_path(:category_id => 13)
          = link_to " 楼盘评测", information_index_path(:category_id => 15)
          = link_to " 楼盘活动", information_index_path(:category_id => 19)
          = link_to " 新房", information_index_path(:category_id => 11)
          = link_to " 楼市资讯", information_index_path(:category_id => 28)
          = link_to " 楼市观点", information_index_path(:category_id => 30)
    .panel.panel-primary
      .panel-heading
        %h3.panel-title 热门资讯
      .panel-body
        %ul
          - @hot.each do |hot|
            %li
              = link_to hot.title.first(16), hot, :class => "lh200"
         
    .panel.panel-primary
      .panel-heading
        %h3.panel-title 资讯排行榜
      .panel-body
        %ul
          - @list.each do |list|
            %li
              = link_to list.title.first(16), list, :class => "lh200"
    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          楼盘推荐
          %a.pull-right.f14{href: "#"} 更多>
      .panel-body
        %table.table.table-condensed
          %thead
            %tr{style: "color:#f65c52"}
              %th 楼盘名称
              %th 区属
              %th 价格
            - NewHome.limit(8).each do |item|
              %tr
                %td
                  = link_to item.name, item
                %td
                  = Area.find(item.area_id).name
                %td #{ item.price }元/m&sup2
    / = image_tag("tmp/rightad.jpg", alt: "", :style => "height:477px; width:240px")

app/views/information/index.html.haml
-provide(:title, '泉州房产资讯')
.container
  .mb20.pull-left
    当前位置：
    = render_breadcrumbs
  .clearfix
  .pull-left{ style: "width: 900px;" }
    - @information.each do |information|
      = render information
    .fenye
      .pagination.pull-right{style: "margin-top:0px;"}
        = will_paginate
  = render "right"
/ con end

app/views/information/show.html.haml
-provide(:title, "#{@information.title}-泉州房产资讯")
-provide(:key, "#{@information.keywords}")
-provide(:desc, "#{@information.description}")
.container
  .mb20.pull-left
    当前位置：
    = render_breadcrumbs
  .clearfix
  .pull-left.content{style: "width:900px;"}
    .top
      .l
        %h1
          = @information.title
        %p
          #{@information.created_at.strftime("%Y-%m-%d %H:%M")}　来源: #{@information.source} 点击量: #{@hit}
      .review
        %p
          = @information.description
    .tj
      - Information.limit(4).each do |information|
        = link_to information.title, information, target: "_blank"
    .clearfix
    .news_body
      = @information.content.html_safe
    .same
      -if !@new_home.blank?
        .mb20{style: "border-bottom:1px  dotted #CCC"}
          %table.mb20
            %tr
              %td{width: "250px;"}
                = link_to image_tag(@new_home.new_home_thumb, alt: @new_home.name, :style => "height:150px; width:230px"), @new_home
              %td{width: "400px"}
                %h5.cl
                  [#{Area.find(@new_home.area_id).name}]
                  = link_to @new_home.name, @new_home, target: "_blank" , :class => "cl"
                  %span.label.label-important.ml10{style: "background:#f65c52"}
                    = Status.find(@new_home.status_id).name
                %p 
                楼盘动态：
                -Information.where(["new_home_id = :home_id and category_id = :c_id",{ home_id: @new_home.id, c_id: 26 }]).limit(1).each do |information|
                  = link_to information.title.first(24), information, target: "_blank"
                %p 售楼电话：#{@new_home.tel}
                %p 项目地址：#{@new_home.project_address}
                
              %td{style: "text-align:center"}
                %h3.mt20.cr #{@new_home.price}元/m ²
                = link_to "团购报名",URI.unescape(new_home_path(@new_home.id,:type =>"index#tuangou")), :class => "btn btn-inverse ", :style => "background:#f65c52; color:#FFF",:target => "_blank"


      %h4.cr 相关阅读
      %ul
        - Information.where("category_id= ? and id != ?" ,@information.category_id ,@information.id).limit(6).each do |information|
          %li
            = link_to information.title.first(24), information, target: "_blank"
            = "..." if information.title.length >24
    .clearfix
    .bshare-custom.icon-medium-plus.ml20
      %a.bshare-qzone{title: "分享到QQ空间"}
      %a.bshare-sinaminiblog{title: "分享到新浪微博"}
      %a.bshare-weixin{title: "分享到微信"}
      %a.bshare-renren{title: "分享到人人网"}
      %a.bshare-qqmb{title: "分享到腾讯微博"}
      %a.bshare-neteasemb{title: "分享到网易微博"}
      %a.bshare-more.bshare-more-icon.more-style-addthis{title: "更多平台"}
    %script{charset: "utf-8", src: "http://static.bshare.cn/b/buttonLite.js#style=-1&uuid=&pophcol=2&lang=zh", type: "text/javascript"}
    %script{charset: "utf-8", src: "http://static.bshare.cn/b/bshareC0.js", type: "text/javascript"}

    / end fenxiang
  = render "right"