config/routes.rb
Meifang::Application.routes.draw do
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/map', to: 'static_pages#map', via: 'get'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :categories
  mount Ckeditor::Engine => '/ckeditor'

  resources :information
  resources :new_homes
  resources :group_buyings
  resources :intention_to_registers
  resources :information_sharings
  resources :characters
  resources :about

  match '/intention_to_registers_new_homes', to: 'static_pages#get_new_homes', via: 'get'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :new_home
  belongs_to :album_class

  mount_uploader :url, AlubmUploader
end

app/models/album_class.rb
class AlbumClass < ActiveRecord::Base
  has_many :albums, dependent: :destroy
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :new_home

  mount_uploader :apartment_thumb, ApartmentUploader
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :new_homes
end

app/models/area_range.rb
class AreaRange < ActiveRecord::Base
  has_many :new_homes
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :information, dependent: :destroy
  validates :name, presence: true

  has_ancestry
end

app/models/character.rb
class Character < ActiveRecord::Base
  mount_uploader :character_thumb, CharacterThumbUploader
end

app/models/developers.rb
class Developers < ActiveRecord::Base
  has_many :new_homes, dependent: :destroy
end

app/models/dummy_data.rb
class DummyData < ActiveRecord::Base
  belongs_to :new_home
end

app/models/group_buying.rb
class GroupBuying < ActiveRecord::Base
  belongs_to :new_home
end

app/models/information.rb
class Information < ActiveRecord::Base
  belongs_to :category
  belongs_to :new_home
  belongs_to :information_type

  validates :category, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :keywords, length: { maximum: 100 }
  validates :description, length: { maximum: 200 }

  mount_uploader :information_thumb, InformationThumbUploader

  searchable do
    integer :information_type_id
    integer :category_id
    text :title, :boost => 5
    text :description
    text :content
    time :created_at
  end
end

app/models/information_type.rb
class InformationType < ActiveRecord::Base
  has_many :information
end

app/models/new_home.rb
class NewHome < ActiveRecord::Base
  belongs_to :area
  belongs_to :developers
  belongs_to :status
  belongs_to :section
  belongs_to :property_type
  belongs_to :construction_category
  belongs_to :area_range
  belongs_to :project_features

  has_many :information
  has_many :information_estate_openeds, dependent: :destroy

  has_many :albums, dependent: :destroy
  accepts_nested_attributes_for :albums, :allow_destroy => true

  has_many :group_buyings, dependent: :destroy
  has_many :intention_to_registers, dependent: :destroy

  has_many :apartments, dependent: :destroy
  accepts_nested_attributes_for :apartments, :allow_destroy => true

  VALID_NUMBER_REGEX = /[\d]/
  validates :name, presence: true
  validates :price, format: { with: VALID_NUMBER_REGEX }
  validates :area, presence:true
  validates :developers, presence:true
  validates :status, presence:true

  mount_uploader :new_home_thumb, NewHomeThumbUploader

  searchable do
    text :name, :boost => 5
    integer :area_id
    integer :section_id
    integer :area_range_id
    integer :property_type_id
    integer :price
    integer :status_id
    text :content
    time :created_at
  end
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  has_many :new_homes
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :new_homes
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :new_homes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable #添加该项，注册后要邮箱验证
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/layouts/_footer.html.haml
/ footer
.container.text-center.projectList.pb20.pt20.mt20{style: "border-top: 2px solid #2db8ad; border-bottom: 1px solid #ddd"}
  %a{href: "about#about", target: "_blank"} 关于馨窝
  %a |
  %a{href: "about#con", target: "_blank"}  联系我们
  %a |
  %a{href: "about#join", target: "_blank"}  招聘信息
  %a |
  %a{href: "about#law", target: "_blank"}  法律声明
.text-center.pt10.pb10
  ©2014  馨窝  版权所有
  %a{href: "http://www.miitbeian.gov.cn", target: "_blank"} 闽ICP备14006517号-2
  - unless Rails.env.development?
    %script{"data-turbolinks-eval" => "false", type: "text/javascript"}
      var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1000442424'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s19.cnzz.com/z_stat.php%3Fid%3D1000442424%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));
-if params[:controller]=="static_pages" or params[:controller] == "new_homes" or params[:controller] == "information"
  %a.bshareDiv{href: "http://www.bshare.cn/share"} 分享按钮
  %script{charset: "utf-8", src: "http://static.bshare.cn/b/buttonLite.js#uuid=&style=3&fs=4&textcolor=#fff&bgcolor=#F60&text=分享到", type: "text/javascript"}

app/views/layouts/_header.html.haml
#miniTop
  .miniLogin
    / %label 用户名：
    / %input#username.loginTxtInt{ name: "username", type: "text" }
    / %label 密码：
    / %input#password.loginTxtInt{ name: "password", type: "password" }
    / %input{ name: "action", type: "hidden", value: "login" }
    / %input{ name: "r", type: "hidden", value: "3" }
    / %input.loginBut{ type: "submit", value: "登录" }
    / %a.regBut 注册
    %p
      馨窝网各地分站：
      = link_to "厦门", "http://xm.xinwowang.com", target: "_blank"
      |
      = link_to "漳州", "http://zz.xinwowang.com", target: "_blank"
      |
      = link_to "泉州", "http://qz.xinwowang.com", target: "_blank", :class => "cr"
      |
      = link_to "广州", "http://gz.xinwowang.com", target: "_blank"
      |
      = link_to "深圳", "http://sz.xinwowang.com", target: "_blank"
      |
  .miniright
    = link_to "首页", root_path
    = link_to "新房", new_homes_path
    = link_to "二手房", "#"
    = link_to "团购", '#'
.clearfix
=render 'layouts/header_ad' if params[:controller]=="static_pages"
.container
  .pull-left.mt20
    = link_to image_tag("logo.png"), "http://www.xinwowang.com", target: "_blank"
  .pull-left.f16.pt55.btn-group
    %button.btn.btn-mini.dropdown-toggle{"data-toggle" => "dropdown"}
      泉州站
      %span.caret
    %ul.dropdown-menu{style: "z-index:99999"}
      %li
        %a{href: "http://xm.xinwowang.com", target: "_blank"} 厦门站
      %li
        %a{href: "http://zz.xinwowang.com", target: "_blank"} 漳州站
      %li
        %a{href: "http://gz.xinwowang.com", target: "_blank"} 广州站
      %li
        %a{href: "http://sz.xinwowang.com", target: "_blank"} 深圳站
  .pull-left.mt30.ml30
    .tabbable
      %ul.nav.nav-tabs#myTab{ style: "margin:0;" }
        %li.active
          %a{ "data-toggle" => "tab", href: "#tab1" } 综合
        %li
          %a{ "data-toggle" => "tab", href: "#tab2" } 新房
        %li
          %a{ href: "#tab3" } 租房
        %li
          %a{ href: "#tab4" } 团购
        %li
          %a{ href: "#tab5" } 专题
      .tab-content#myTabContent
        .tab-pane.fade.active.in#tab1
          = form_tag information_index_path, :method => :get, :class => "form-inline m0",name: "myform", :role => "form" do
            = text_field_tag :keyword, params[:keyword], :class => "form-control", :id => "keyword", :style => "width: 525px", :placeholder => "请输入关键字"
            %button.btn.btn-danger{ type: "submit" }
              搜索
        .tab-pane#tab2
          = form_tag new_homes_path, :method => :get, :class => "form-inline m0",name: "myform", :role => "form" do
            = text_field_tag :keyword, params[:keyword], :class => "form-control", :id => "keyword", :style => "width: 525px", :placeholder => "请输入关键字"
            %button.btn.btn-danger{ type: "submit" }
              搜索
        #tab3.tab-pane
/ 导航
:javascript
  jQuery(function($) {
    $(document).ready( function() {
      $('.newnav').stickUp();
    });
  });
%div{ style: "height: 20px" }
#toc_container.newnav{ align: "center" }
  = link_to "首页", root_path, target: "_blank"
  |
  = link_to "资讯", information_index_path, target: "_blank"
  |
  = link_to "新房", new_homes_path, target: "_blank"
  |
  = link_to "团购", '#', target: "_blank"
  |
  = link_to "地图找房", map_path, target: "_blank"
  |
  %a{href: "#", target: "_blank"}> 租房
  |
  %a{href: "#", target: "_blank"} 二手房
/ header end

app/views/layouts/_header_ad.html.haml
.container
  - if mobile?
    %div{style: "border: 1px solid rgb(221, 221, 221); height:80px"}
      = image_tag("swf/1.gif", alt: "")
    %div{style: "border: 1px solid rgb(221, 221, 221); height:80px"}
      = image_tag("swf/2.gif", alt: "")
    %div{style: "border: 1px solid rgb(221, 221, 221); height:80px"}
      = image_tag("swf/3.gif", alt: "")
  - else
    %div{style: "border: 1px solid rgb(221, 221, 221); height:80px"}
      %embed{height: "80px;",  src:"#{asset_path 'swf/1.swf'}", width: "1170px;",wmode:"opaque"}
    %div{style: "border: 1px solid rgb(221, 221, 221); height:80px"}
      %embed{height: "80px;", src:"#{asset_path 'swf/2.swf'}", width: "1170px;",wmode:"opaque"}
    %div{style: "border: 1px solid rgb(221, 221, 221); height:80px"}  
      %embed{height: "80px;", src:"#{asset_path 'swf/3.swf'}", width: "1170px;",wmode:"opaque"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title><%= full_title(yield(:title)) %></title>
  <meta name="keywords" content=<%= full_key(yield(:key)) %> />
  <meta name="description" content=<%= full_desc(yield(:desc)) %>/>
  <link rel="shortcut icon" href="<%= asset_path("favicon.ico") %>" />
  <%= stylesheet_link_tag "application",
                          "custom",
                          "custom/base",
                          "custom/common",
                          "custom/font-awesome.min",
                          "custom/bootstrop3code",
                          params[:controller],
                          media: "all", "data-turbolinks-track" => true %>
  <!--[if lte IE 6]>
    <%= stylesheet_link_tag "bootstrap/bootstrap-ie6.css", media: "all", "data-turbolinks-track" => true %>
  <![endif]-->
  <!--[if lte IE 7]>
    <%= stylesheet_link_tag "bootstrap/ie.css", media: "all", "data-turbolinks-track" => true %>
  <![endif]-->

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <% if value =="您的信息我们已经收到，会尽快的联系您。是否继续完成信息登记？" %>
        <SCRIPT LANGUAGE="JavaScript">
          var bln=confirm("是否继续完善登记信息，是点击“确定” 否点击“取消”？")
          if (bln==true){
            window.open('/intention_to_registers');
          }
          else{

         }   
        </script>
      <% else %>
        <SCRIPT LANGUAGE="JavaScript">
          alert("<%= value %>")
        </script>
      <% end %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <% if mobile? %>
      <%= javascript_include_tag "application",
                              params[:controller],
                              "custom/ad_ls",
                              "data-turbolinks-track" => true %>
    <% else %>
      <%= javascript_include_tag "application",
                                params[:controller],
                                "custom/ad_ls",
                                "custom/stickUp.min",
                                "data-turbolinks-track" => true %>
    <% end %>

    <!--[if lte IE 6]>
      <%= javascript_include_tag "bootstrap/bootstrap-ie.js", "data-turbolinks-track" => true %>
    <![endif]-->
  </body>
  </html>

app/views/shared/_intention_to_register_form.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title
      意向登记
      %span.f12{style: "font-weight:normal"} |为您提供优质的房源
  .panel-body.yxdj
    = form_for(@intention_to_register) do |f|
      %table.table-condensed
        %tr
          %td 姓名:
          %td
            = f.text_field :name, placeholder: "请输入联系姓名", style: "width: 130px"
        %tr
          %td QQ :
          %td
            = f.text_field :qq, placeholder: "请输入联系qq", style: "width: 130px"
        %tr
          %td 电话:
          %td
            = f.text_field :tel, placeholder: "请输入联系电话", style: "width: 130px"
        / %tr
        /   %td 区域
        /   %td
        /     = select_tag 'intention_to_register[area]', "<option value=''>#{t('请选择区域')}</option>".html_safe+options_from_collection_for_select(Area.all, "id", "name"), { onchange: "set_new_homes(this.value)", style: "width: 140px" }
        %tr
          %td 楼盘:
          %td
            = select_tag 'intention_to_register[new_home_id]', "<option value=''>#{t('请选择楼盘')}</option>".html_safe, { style: "width: 140px" }
        %tr
          %td
          %td
            = f.submit "立刻报名", class: "btn btn-danger btn-mini", style: "height: 28px"
:javascript
  function set_new_homes(value){
    $.ajax({
      type: 'get',
      url: 'intention_to_registers_new_homes?area_id=' + value,
      data: 'text',
      success: function(data){
        $("#intention_to_register_new_home_id").html(data);
      }
    }
  )
  }